name: hpnet-updated
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - orbingol
  - xformers
dependencies:
  - python=3.9
  - numpy
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision=0.15.0
  - tensorboard
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - transforms3d
  - h5py
  - trimesh
  - scipy
  - geomdl
  - pykdtree
  - seaborn==0.11.0
  - matplotlib==3.3.3
  - pip
  - pip:
    - torch_scatter
    - lapsolver==1.1.0
    - open3d
    - ipdb==0.12.3
    - lap==0.4.0
